### ISSUE TITLE
Support setting units and description

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-mucho#14]
Rasterio 1.0 comes with some methods to set metadata for band-level units and descriptions. The methods are only available on a dataset writer object. In the case of `riomucho`, the code calling it never has access to that object. All it sees is:

```
with riomucho.RioMucho(..., dst_path, ...) as rm:
    rm.run(jobs)
```

What's the best solution? Do we expose these methods on the rio mucho object? Or is there a more generalizable way for us to reach into the dataset object methods from a rio-mucho caller?

See https://github.com/mapbox/rio-toa/issues/23

thoughts @dnomadb @sgillies ?

**Comment by sgillies** [comment]
Almost 2 years later: I propose that we keep riomucho out of the metadata business. To do that, we need to let the constructor accept open dataset objects as well as paths. Yes?
