### ISSUE TITLE
Hide/resolve Rasterio transform warnings

### ISSUE THREAD

**Issue by jqtrde** [mapbox/rio-mucho#15]
I'm seeing the following error pretty consistently:

```
~/pxm/venv/lib/python2.7/site-packages/riomucho/__init__.py:98: FutureWarning: GDAL-style transforms are deprecated and will not be supported in Rasterio 1.0.
  self.options['transform'] = guard_transform(self.options['transform'])
```

I don't have a good sense of what resolving this looks like yet, just wanted to flag.

**Comment by dnomadb** [comment]
@jacquestardie which version are you on? This should have been resolved in https://github.com/mapbox/rio-mucho/pull/13

**Comment by jqtrde** [comment]
`pip freeze` within the virtualenv we build for pxm returns `rio-mucho==0.2.2`

**Comment by jqtrde** [comment]
Per chat, this behavior is intentional.
