### ISSUE TITLE
[Question] Implementing a global shared counter in riomucho

### ISSUE THREAD

**Issue by jocdiazm** [mapbox/rio-mucho#16]
Dear dev. team,

I've been struggling to create a global shared counter for "processed blocks of a raster" in a simple console progress bar in a _riomucho_ implementation for an academic purpose.

According to  [this answer](http://stackoverflow.com/a/21681534) in SO ,  I'm trying to create a class counter object and passing it to the global_arguments parameter to be used in my processing function as:

``` python

block_counter=Counter()
#Pass the variable to  the global args parameter dictionary "g_args" 
def my_rasterfun(...):
     #do something here
     g_args["block_counter"].increment()
     print (g_args["block_counter"].value)
     return my_output
```

And the value _does_ increment linearly (exactly as expected for a progressbar) as opposed to simply defining a multiprocessing value,  but the final value printed is quite different from the length of the `windows` argument passed to `riomucho`, and I assume they should be equal. (shouldn't they?)

I'm a beginner programmer, so maybe I'm missing something...

Thank you so much for time!

**Comment by sgillies** [comment]
Apologies for neglecting this question. You've probably solved it by now. Progress bars are out of this project's scope, but the place to update a progress bar is in the main process when `self.pool.imap_unordered` yields results.
