### ISSUE TITLE
Bypass multiprocessing if single worker

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-mucho#9]
Multiprocessing isn't always pleasant for debugging. 

Maybe we could do [something like this](https://github.com/mapbox/rio-color/blob/master/rio_color/scripts/cli.py#L93-L110) where we only go multiprocess if we have jobs > 1

**Comment by dnomadb** [comment]
@perrygeo do you thinking mocking the pool itself would be a good approach?

**Comment by perrygeo** [comment]
fixed by #10
